name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack src/REE.PAK -c Release --no-build -o out
    - name: Create zip
      run: |
        dotnet publish -c Release -o archive --no-build
        cd archive
        rm *.pdb *.deps.json
        cp -r ../Projects . && mv Projects projects
        zip -r ../out/ree-pak-tools.zip *
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: REE.PAK
        path: out/**/*
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: |
          out/*.nupkg
          out/*.zip
    - name: Publish to nuget.org
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push out/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
